In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().parent
sys.path.insert(0, str(ROOT / "code"))

from mdp.task import Task
from mdp.catalogue import Catalogue
from mdp.state import Specification, Term
from mdp.action import *
from env.apollo.generator import ApolloGenerator
from env.environment import evaluate_specification
from env.result_cache import ResultCache

A. Load task and create a catalogue

In [2]:
task_1 = Task.from_yaml(0,  yaml_path=ROOT / "dataset/dataset_1/dataset.yaml") # ApolloModeChoice
task_2 = Task.from_yaml(1,  yaml_path=ROOT / "dataset/dataset_2/dataset.yaml") # ApolloRouteChoice
task_3 = Task.from_yaml(2,  yaml_path=ROOT / "dataset/dataset_3/dataset.yaml") # Decisions
task_4 = Task.from_yaml(3,  yaml_path=ROOT / "dataset/dataset_5/dataset.yaml") # 1987_NL_VoT
task_5 = Task.from_yaml(4,  yaml_path=ROOT / "dataset/dataset_6/dataset.yaml") # 2009_Norway_VoT
task_6 = Task.from_yaml(5,  yaml_path=ROOT / "dataset/dataset_7/dataset.yaml") # 2013_Arentze
task_7 = Task.from_yaml(6,  yaml_path=ROOT / "dataset/dataset_8/dataset.yaml") # 2014_spain_parkingChoice
task_8 = Task.from_yaml(7,  yaml_path=ROOT / "dataset/dataset_9/dataset.yaml") # 2018 LPMC
task_9 = Task.from_yaml(8,  yaml_path=ROOT / "dataset/dataset_10/dataset.yaml") # 2018_Optima
task_10 = Task.from_yaml(9,  yaml_path=ROOT / "dataset/dataset_11/dataset.yaml") # 2019_vanCranenburgh      

tasks = [task_1, task_2, task_3, task_4, task_5, task_6, task_7, task_8, task_9, task_10]

# Define one task
task = task_1
catalogue = Catalogue.from_tasks(tasks)
specification_manager = Specification(catalogue=catalogue)
action_space = ActionSpace(task, catalogue, specification_manager,linear_additive=True)
generator = ApolloGenerator(task)

1. Linear additive

In [3]:
print("rewards_path", task.rewards_path)
print("yaml_path", task.yaml_path)
print("dataset_path",task.dataset_path)

rewards_path /Users/gnova/Developer/Delphos-core/dataset/dataset_1/rewards.sqlite
yaml_path /Users/gnova/Developer/Delphos-core/dataset/dataset_1/dataset.yaml
dataset_path /Users/gnova/Developer/Delphos-core/dataset/dataset_1/2019_apollo_modechoice_formatted.csv

In [4]:
specification = action_space.create_initial_specification()
backend_specification = specification_manager.to_backend(specification)
apollo_specification = generator.build_apollo_specification(backend_specification)

evaluate_specification(
    task,
    apollo_specification
    )

,task_name,specification,numParams,numResids,maximum,vcHessianConditionNumber,successfulEstimation,LL0,LLC,LLout,rho2_0,adjRho2_0,rho2_C,adjRho2_C,AIC,BIC,eigValue,timeTaken,nFreeParams,skipped
0,ApolloModeChoice,1110_2110_3110_4110_5000_6110_7000,7.0,5600.0,-4670.988194,5.802145e-07,1,-6607.093673,-5430.886635,-4670.988194,0.293034,0.291975,0.139922,0.139185,9355.976387,9402.39004,-25.901553,0.442298,7.0,0

In [5]:
specification_2 = action_space.create_initial_specification()
specification_2, _ = action_space.apply_action(specification_2, action_index=3)

backend_specification_2 = specification_manager.to_backend(specification_2)
apollo_specification_2 = generator.build_apollo_specification(backend_specification_2)



evaluate_specification(
    task,
    apollo_specification_2,
    )

,task_name,specification,numParams,numResids,maximum,vcHessianConditionNumber,successfulEstimation,LL0,LLC,LLout,rho2_0,adjRho2_0,rho2_C,adjRho2_C,AIC,BIC,eigValue,timeTaken,nFreeParams,skipped
0,ApolloModeChoice,1112_2110_3110_4110_5000_6110_7000,16.0,5600.0,-4554.368737,1.481029e-07,1,-6607.093673,-5430.886635,-4554.368737,0.310685,0.308263,0.161395,0.159001,9140.737474,9246.825824,-6.232372,1.012997,16.0,0